[project]
name = "mysite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.8.1",
    "django==5.2",
    "sqlparse==0.5.3",
    "typing-extensions==4.13.2 ; python_full_version < '3.11'",
]
